ROAD_STRAIGHT = "ROAD_STRAIGHT"
ROAD_INTERSECTION = "ROAD_INTERSECTION"

#
SUNNY = "SUNNY"
CLOUDY = "CLOUDY"
RAINY = "RAINY"

#
DAY = "DAY"
NIGHT = "NIGHT"

#
FORWARD = "FORWARD"
LEFT = "LEFT"
RIGHT = "RIGHT"

#
VERTICAL = "VERTICAL"
PARALLEL = "PARALLEL"

#
MOVING = "MOVING"
ROAD_PAINTING = "ROAD_PAINTING"
OBJECTS = "OBJECTS"

#
PEDESTRIAN = "PEDESTRIAN"
CYCLIST = "CYCLIST"
CAR = "CAR"
HEAVY_VEHICLE = "HEAVY_VEHICLE"
MOTORBIKE = "MOTORBIKE"
TRAFFIC_LIGHT = "TRAFFIC_LIGHT"
ROADSIDE_TREE = "ROADSIDE_TREE"
RAILROAD_CROSSING = "RAILROAD_CROSSING"
GUARDRAIL = "GUARDRAIL"
WHITE_LINE = "WHITE_LINE"
WHITE_CENTER_LINE = "WHITE_CENTER_LINE"
STOP_LINE = "STOP_LINE"
TRAFFIC_SIGN = "TRAFFIC_SIGN"
MAXIMUM_SPEED_SIGN = "MAXIMUM_SPEED_SIGN"
ONEWAY_SIGN = "ONEWAY_SIGN"
CURB = "CURB"
PEDESTRIAN_CROSSING_ZONE = "PEDESTRIAN_CROSSING_ZONE"
BICYCLE_CROSSING_ZONE = "BICYCLE_CROSSING_ZONE"
WALL = "WALL"
POLE_GROUP = "POLE_GROUP"